apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    rampcode: deploy
  name: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    env: dev
    name: nginx
  type: ClusterIP
status:
  loadBalancer: {}
