apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-affinity
  template:
    metadata:
      labels:
        app: node-affinity
    spec:
      containers:
      - name: k8s-demo
        image: nginx
        ports:
        - name: nodejs-port
          containerPort: 3000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In           #In, NotIn, Exists, DoesNotExist. Gt, and Lt.
                values:
                - dev
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In           #In, NotIn, Exists, DoesNotExist. Gt, and Lt.
                values:
                - node01
          - weight: 2
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
