apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: secret-nginx
  template:
    metadata:
      labels:
        name: secret-nginx
    spec:
      containers:
      - name: secret-containers
        image: nginx
        volumeMounts:
        - name: test
          mountPath: "/secrets/"
          readOnly: yes
      volumes:
      - name: test
        secret:
          secretName: test
