apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: my-app
    version: v2
spec:
  selector:
    app: my-app
    version: v2.0.0
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
